#!/usr/bin/python3

import sys
import os
from git import Repo

if len(sys.argv) != 3:
    print("Usage: python compare-releases <release1> <release2>")
    sys.exit(1)

release1 = sys.argv[1]
release2 = sys.argv[2]

repository_path = os.getcwd()
try:
    repo = Repo(repository_path)

    commit1 = repo.commit(release1)

    commit2 = repo.commit(release2)

    commit_diff = repo.git.diff(commit1, commit2)

    print(commit_diff)
except Exception as e:
    print(f"An error occurred: {e}")
